// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-wrVQa54lQ_WM8a0vrJJRZFUlnkk6rR4',
    appId: '1:627066273315:web:1749af293aedb070affb96',
    messagingSenderId: '627066273315',
    projectId: 'dav1dct',
    authDomain: 'dav1dct.firebaseapp.com',
    storageBucket: 'dav1dct.firebasestorage.app',
    measurementId: 'G-2G752SN69D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GTynqoUg4HS9m990JwbIf5KVwFgxgeU',
    appId: '1:627066273315:android:160892230f793bcdaffb96',
    messagingSenderId: '627066273315',
    projectId: 'dav1dct',
    storageBucket: 'dav1dct.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC5vtKdqrFjNifjdrFvl6P3r0Zfh5ffTs',
    appId: '1:627066273315:ios:1dba359686e69644affb96',
    messagingSenderId: '627066273315',
    projectId: 'dav1dct',
    storageBucket: 'dav1dct.firebasestorage.app',
    iosBundleId: 'com.example.projectUasPlantcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC5vtKdqrFjNifjdrFvl6P3r0Zfh5ffTs',
    appId: '1:627066273315:ios:1dba359686e69644affb96',
    messagingSenderId: '627066273315',
    projectId: 'dav1dct',
    storageBucket: 'dav1dct.firebasestorage.app',
    iosBundleId: 'com.example.projectUasPlantcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-wrVQa54lQ_WM8a0vrJJRZFUlnkk6rR4',
    appId: '1:627066273315:web:2617bfd8ee304949affb96',
    messagingSenderId: '627066273315',
    projectId: 'dav1dct',
    authDomain: 'dav1dct.firebaseapp.com',
    storageBucket: 'dav1dct.firebasestorage.app',
    measurementId: 'G-Y7MHVW79PF',
  );

}