name: project_uas_plantcare
description: "UAS PAB2 Firebase."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.6.0
  firebase_storage_web: ^3.7.0
  file_picker: ^8.0.0
  image_picker: ^1.1.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.18
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
